spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
  server:
    enable-self-preservation: false
  instance:
    prefer-ip-address: true
logging:
  path: /var/log/
